services:
  - type: web
    name: artem-landing
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /index.html
        name: Cache-Control
        value: no-cache
